# Generated by Django 5.1.4 on 2025-01-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_profile_picture_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='ProfilePicture.png', upload_to='images/'),
        ),
    ]
